version: "2"
metadata:
  category: Payments
  name: BitcartCC
  version: 0.6.5.1
  tagline: BitcartCC is a self-hosted payment processor and developer solutions platform for cryptocurrencies
  description: "BitcartCC provides light-weight, but secure and easy-to-use solutions for merchants and developers"
  developer: BitcartCC
  website: https://bitcartcc.com
  repo: https://github.com/bitcartcc/bitcart
  support: https://bitcartcc.com/#community
containers:
  admin:
    restart: unless-stopped
    image: bitcartcc/bitcart-admin:stable
    expose:
      - "4000"
    command: yarn start
    environment:
      BITCART_ADMIN_LOG_FILE: bitcart.log
      BITCART_ADMIN_API_URL: http://$APP_BITCARTCC_BACKEND_IP:8000
    ports:
      - 4000:4000
    links:
      - backend
  backend:
    depends_on:
      - bitcoin
      - database
      - redis
    links:
      - bitcoin
      - database
      - redis
    restart: unless-stopped
    image: bitcartcc/bitcart:stable
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: bash -c "alembic upgrade head && gunicorn -c gunicorn.conf.py main:app"
    environment:
      IN_DOCKER: false
      LOG_FILE: bitcart.log
      BITCART_DATADIR: /datadir
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      REDIS_HOST: redis://$APP_BITCARTCC_REDIS_IP
      DB_HOST: $APP_BITCARTCC_DATABASE_IP
    user: 1000:1000
    expose:
      - "8000"
    volumes:
      - data/bitcart:/datadir
    ports:
      - 8000:8000
  bitcoin:
    restart: unless-stopped
    image: bitcartcc/bitcart-btc:stable
    environment:
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      IN_DOCKER: false
    expose:
      - "5000"
    volumes:
      - data/bitcoin:/data
  database:
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: bitcart
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data/postgres:/var/lib/postgresql/data
    expose:
      - "5432"
  redis:
    restart: unless-stopped
    image: redis:alpine
    expose:
      - "6379"
  store:
    restart: unless-stopped
    image: bitcartcc/bitcart-store:stable
    expose:
      - "3000"
    command: yarn start
    environment:
      BITCART_STORE_API_URL: http://$APP_BITCARTCC_BACKEND_IP:8000
    ports:
      - 3000:3000
    links:
      - backend
  worker:
    depends_on:
      - backend
    links:
      - backend
    restart: unless-stopped
    image: bitcartcc/bitcart:stable
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: python3 worker.py
    environment:
      IN_DOCKER: false
      LOG_FILE: bitcart.log
      BITCART_DATADIR: /datadir
      BTC_NETWORK: $BITCOIN_NETWORK
      BTC_LIGHTNING: true
      REDIS_HOST: redis://$APP_BITCARTCC_REDIS_IP
      DB_HOST: $APP_BITCARTCC_DATABASE_IP
    user: 1000:1000
    expose:
      - "9020"
    volumes:
      - data/bitcart:/datadir
