# SPDX-FileCopyrightText: 2022 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Social
  name: Synapse
  version: 1.59.1
  tagline: Matrix homeserver
  description: Description is coming soon.
  developers:
    Matrix: https://matrix.org
  dependencies: []
  repo: https://github.com/matrix-org/synapse
  support: https://matrix.to/#/#synapse:matrix.org
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  torOnly: false
containers:
  - image: ghcr.io/runcitadel/synapse:develop@sha256:9baa8cb96ab6b844fb47714c51ec683b8962a3a90de3de3daa6f88fddc5e3bdb
    entrypoint: bash
    command: -c './start.py generate && ./start.py migrate_config && exec ./start.py'
    port: 8008
    environment:
      UID: "1000"
      GID: "1000"
      SYNAPSE_HTTP_PORT: 8008
      SYNAPSE_SERVER_NAME: ${APP_HIDDEN_SERVICE}
      SYNAPSE_REPORT_STATS: yes
      SYNAPSE_ENABLE_REGISTRATION: yes
      SYNAPSE_NO_TLS: yes
    name: server
    data:
      - data/synapse:/data
    hiddenServicePorts:
      - 80
      - 8008
