# SPDX-FileCopyrightText: 2022 Jonathan Zernik
# SPDX-FileCopyrightText: 2022 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v4.yml

citadel_version: 4

metadata:
  category: Explorers
  name: WoofBot
  version: "0.1.0"
  tagline: A chatbot for your personal node.
  description: >-
    WoofBot is a chat bot that runs on your personal Bitcoin node and sends telegram notifications
    based on pre-configured conditions: addresses, transactions, new-blocks and price changes.
  developers:
    WoofBotApp: https://github.com/woofbotapp
  permissions:
    - bitcoin
  repo:
    Public: https://github.com/woofbotapp/woofbotapp
  support: https://github.com/woofbotapp/woofbotapp/discussions
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  path: ""
  defaultPassword: $APP_SEED

services:
  web:
    image: woofbot/woofbot:v0.2.0@sha256:bfcc02f752963eaf9f9c3bf2776e032194d218b0037f3c54ed19d8872a7f241b
    restart: on-failure
    stop_grace_period: 1m
    environment:
      MONGODB_URI: "mongodb://${APP_WOOFBOT_MONGODB_IP}:27017/woofbot"
      APP_PORT: "8080"
      APP_SEED: $APP_SEED_2
      APP_PASSWORD: $APP_SEED
      APP_BITCOIN_NODE_IP: $APP_BITCOIN_NODE_IP
      APP_BITCOIN_RPC_USER: $APP_BITCOIN_RPC_USER
      APP_BITCOIN_RPC_PASS: $APP_BITCOIN_RPC_PASS
      APP_BITCOIN_RPC_PORT: $APP_BITCOIN_RPC_PORT
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0.9@sha256:37e84d3dd30cdfb5472ec42b8a6b4dc6ca7cacd91ebcfa0410a54528bbc5fa6d
    user: 1000:1000
    restart: on-failure
    stop_grace_period: 1m
    mounts:
      data:
        data/db: /data/db
