# SPDX-FileCopyrightText: Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v4.yml

citadel_version: 4

metadata:
  category: Electrum Servers
  name: Electrs
  version: 0.9.9
  tagline: The electrum server for personal use with the lowest resource usage
  description: >-
    Electrs provides a fast Electrum server for personal use and to share with friends and family.
    It is very fast and does not consume much resources.
  developers: 
    Roman Zeyde: https://romanzey.de/
  permissions:
    - bitcoind
  repo:
    Electrs: https://github.com/romanz/electrs
  support: https://github.com/romanz/electrs/issues
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  implements: electrum

services:
  main:
    image: nginx:1.21.6@sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767
    init: true
    restart: on-failure
    mounts:
      data:
        data/nginx.conf: /etc/nginx/nginx.conf
        data/www: /usr/share/nginx/html
    port: 80

  electrum:
    port_priority: "Required"
    port: 50001
    image: ghcr.io/runcitadel/electrs:v0.9.9
    mounts:
      bitcoin: /bitcoin
      data:
        data/electrs: /data
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "bitcoin"
      ELECTRS_DAEMON_DIR: "/bitcoin"
      ELECTRS_DAEMON_RPC_ADDR: "${BITCOIN_IP}:${BITCOIN_RPC_PORT}"
      ELECTRS_DAEMON_P2P_ADDR: "${BITCOIN_IP}:${BITCOIN_P2P_PORT}"
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:50001"
      ELECTRS_SERVER_BANNER: "Electrs running on Citadel"
      ELECTRS_DB_DIR: "/data/db"
