name: Check app updates

on:
  workflow_dispatch:
  schedule: 
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1

      - name: Check for updates
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          git clone https://github.com/runcitadel/app-cli
          cd app-cli
          cargo run --features=cli,dev-tools -- update ../apps
          cd ..
          rm -rf app-cli
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "Update apps"  || true
          git push
