# SPDX-FileCopyrightText: 2022 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  name: WordPress
  version: 6.0.1
  category: Blog
  tagline: Host a blog on your Citadel
  description: WordPress
  developers:
    WordPress Developers: https://wordpress.org
  repo: https://github.com/WordPress/WordPress
  support: https://wordpress.org
  gallery:
    - 1.png
    - 2.png
    - 3.png
containers:
  - name: main
    image: wordpress:6.0.1@sha256:999392cfea3cee05633a0a9026fc46df637d8291e631a1afa85099ad2553e3eb
    depends_on:
      - db
    data:
      - data/wp:/var/www/html
    port: 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: $APP_WORDPRESS_DB_IP
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: somewordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct');
  - name: db
    image: mariadb:10.7.3-focal@sha256:07e06f2e7ae9dfc63707a83130a62e00167c827f08fcac7a9aa33f4b6dc34e0e
    user: 1000:1000
    data:
      - data/db:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: somewordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
